#:schema node_modules/wrangler/config-schema.json
name = "my-bltdiy"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"
main = "./build/client/index.js"

[pages]
build_output_dir = "build/client"
pages_build_output_dir = "build/client"

[build]
command = "pnpm run build"
output_dir = "build/client"

[env.production]
name = "my-bltdiy-production"

[env.preview]
name = "my-bltdiy-preview"
