#:schema node_modules/wrangler/config-schema.json
name = "my-bolt"
compatibility_date = "2024-01-01"
workers_dev = true

[site]
bucket = "./build/client"
entry-point = "functions/[[path]].ts"

[build]
command = "corepack enable && corepack prepare pnpm@8 --activate && pnpm install && pnpm run build"
pages_build_output_dir = "build/client"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
PNPM_VERSION = "8"

[env.production]
name = "my-bolt-prod"

[env.staging]
name = "my-bolt-staging"
