#:schema node_modules/wrangler/config-schema.json
name = "my-bltdiy"
compatibility_date = "2024-01-01"
workers_dev = true

[site]
bucket = "./build/client"
entry-point = "functions/[[path]].ts"

[build]
command = "pnpm run build"
pages_build_output_dir = "build/client"

[env.production]
name = "my-bltdiy-prod"

[env.staging]
name = "my-bltdiy-staging"
