name: Docs CI/CD

on:
  push:
    branches:
      - main
<<<<<<< HEAD
    paths:
      - 'docs/**' # This will only trigger the workflow when files in docs directory change
=======
>>>>>>> 48d3b799435c5f563650cf3ade719ed99182eb8e
permissions:
  contents: write
jobs:
  build_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
<<<<<<< HEAD
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
=======
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
>>>>>>> 48d3b799435c5f563650cf3ade719ed99182eb8e
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material
<<<<<<< HEAD
      - run: mkdocs gh-deploy --force
=======
      - run: mkdocs gh-deploy --force 
>>>>>>> 48d3b799435c5f563650cf3ade719ed99182eb8e
